// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0us9hx1VVrKl-41iBGzXtG9KT8JmVsBM',
    appId: '1:568637381346:web:05360e721c0064ae3adcbb',
    messagingSenderId: '568637381346',
    projectId: 'my-project-sy-01',
    authDomain: 'my-project-sy-01.firebaseapp.com',
    storageBucket: 'my-project-sy-01.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwBNEwvcs-PHW212UhyvQywX4Ggk0HlYs',
    appId: '1:568637381346:android:56e0d25e60ebbb303adcbb',
    messagingSenderId: '568637381346',
    projectId: 'my-project-sy-01',
    storageBucket: 'my-project-sy-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrcGJOyvvBoqw9YC1T7gztXmyeDVNxC2k',
    appId: '1:568637381346:ios:09b77ef2dde488e93adcbb',
    messagingSenderId: '568637381346',
    projectId: 'my-project-sy-01',
    storageBucket: 'my-project-sy-01.appspot.com',
    iosClientId: '568637381346-hr93ok4lmdjeqj3onkclsbdvn6trti5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );
}
